THPTUDWeb/Controllers/LienheController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace THPTUDWeb.Controllers
{
    public class LienheController : Controller
    {
        // GET: Lienhe
        public ActionResult Index()
        {
            return View();
        }
    }
}

THPTUDWeb/Controllers/ModuleController.cs
using MyClass.DAO;
using MyClass.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace THPTUDWeb.Controllers
{
    public class ModuleController : Controller
    {
        // GET: Module
        MenusDAO menusDAO = new MenusDAO();
        ///////////////////////////////////////////////////////////////////////////
        // GET: Mainmenu
        public ActionResult MainMenu()
        {
            List<Menus> list = menusDAO.getListByParentId(0, "MainMenu");
            return View("MainMenu", list);
        }
        ///////////////////////////////////////////////////////////////////////////
        // GET: MainmenuSub
        public ActionResult MainMenuSub(int id)
        {
            List<Menus> list = menusDAO.getListByParentId(id, "MainMenu");
            //Trả về dòng hiện hành của menu có id = id
            Menus menus = menusDAO.getRow(id);
            if (list.Count == 0)//menu không có cấp con
            {
                return View("MainMenuSub_0", menus);
            }
            else//menu có cấp con
            {
                ViewBag.Menu2cap = menus;
                return View("MainMenuSub_1", list);
            }
        }
        ///////////////////////////////////////////////////////////////////////////
        public ActionResult Slider()
        {
            SlidersDAO slidersDAO = new SlidersDAO();
            List<Sliders> list = slidersDAO.getListByPosition("Slider");
            return View("Slider", list);

        }
        ///////////////////////////////////////////////////////////////////////////
        public ActionResult CategoriesList()
        {
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            List<Categories> list = categoriesDAO.getListByPareantId(0);
            return View("CategoriesList", list);

        }

        ///////////////////////////////////////////////////////////////////////////
        ///Footer Menu
        public ActionResult MenuFooter()
        {
            MenusDAO menusDAO = new MenusDAO();
            List<Menus> list = menusDAO.getListByParentId(0, "Footer");
            return View("MenuFooter", list);
        }

        // Action để hiển thị danh sách nhà cung cấp
        public ActionResult SuppliersList()
        {
            SuppliersDAO suppliersDAO = new SuppliersDAO();
            List<Suppliers> list = suppliersDAO.getList("Index");
            return View("SuppliersList", list);
        }
        ///////////////////////////////////////////////////////////////////////////
        public ActionResult PageList()
        {
            PostsDAO postsDAO = new PostsDAO();
            List<Posts> list = postsDAO.getList("Index","page");
            return View("PageList", list);
        }
    }
}

THPTUDWeb/Controllers/SiteController.cs
using MyClass.DAO;
using MyClass.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace THPTUDWeb.Controllers
{
    public class SiteController : Controller
    {
        LinksDAO linksDAO = new LinksDAO();
        // GET: Site
        public ActionResult Index(string slug = null)
        {
            if (slug == null)
            {
                //Chuyền về trang chủ
                return this.Home();
            }
            else
            {
                //Tìm slug có trong bảng Link
                Links links = linksDAO.getRow(slug);
                //Kiểm tra slug có tồn tại trong bảng Links hay không?
                if (links != null)
                {
                    //Lấy ra Type trong bảng Link
                    string typelink = links.Type;
                    switch (typelink)
                    {
                        case "category":
                            {
                                return this.ProductCategory(slug);
                            }
                        case "topic":
                            {
                                return this.PostTopic(slug);
                            }
                        case "supplier":
                            {
                                return this.ProductSupplier(slug);
                            }
                        case "page":
                            {
                                return this.PostPage(slug);
                            }
                        default:
                            {
                                return this.Error404(slug);
                            }
                    }
                }
                else
                {
                    //Slug không có trong bảng Links
                    //slug có trong bảng product?
                    //slug có trong bảng Post với PostType==post?
                    ProductsDAO productsDAO = new ProductsDAO();
                    PostsDAO postsDAO = new PostsDAO();
                    SuppliersDAO suppliersDAO = new SuppliersDAO();
                    //Tìm slug có trong bảng Products
                    Products products = productsDAO.getRow(slug);
                    if (products != null)
                    {
                        return this.ProductDetail(slug);
                    }
                    else
                    {
                        //Trường hợp là Post
                        Posts posts = postsDAO.getRow(slug);
                        if (posts != null)
                        {
                            return this.PostDetail(posts);
                        }
                        else
                        {
                            Suppliers supplier = suppliersDAO.getRow(slug);
                            if (supplier != null)
                            {
                                return this.ProductSupplier(slug);
                            }
                        }
                        return this.Error404(slug);
                    }
                }
            }
        }
        /////////////////////////////////////////////////////////////////////////////
        //Trang chu
        public ActionResult Home()
        {
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            List<Categories> list = categoriesDAO.getListByPareantId(0);
            return View("Home", list);
        }
        /////////////////////////////////////////////////////////////////////////////
        //Site/Product
        //HIỂN THỊ TẤT CẢ SẢN PHẨM KHÔNG PHÂN BIỆT
        public ActionResult Product()
        {
            ProductsDAO productsDAO = new ProductsDAO();
            List<ProductInfo> list = productsDAO.getListBylimit(50);
            return View("Product", list);
        }
        public ActionResult Post()
        {
            return View("Post");
        }
        /////////////////////////////////////////////////////////////////////////////
        //Site/ProductCategory
        public ActionResult ProductCategory(string slug)
        {
            //Lấy categories đưa vào Slug
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            Categories categories = categoriesDAO.getRow(slug);
            //Hiển thị nội dung của mẩu tin
            ViewBag.Categories = categories;
            //Hiển thị toàn bộ các sản phẩm ứng với từng loại sản phẩm
            //Hiển thị theo 3 cấp: Cha - Con - Con của con
            List<int> listcatid = new List<int>();
            //Cấp 1
            listcatid.Add(categories.Id);
            //Cấp 2
            List<Categories> listcategories2 = categoriesDAO.getListByPareantId(categories.Id);
            if (listcategories2.Count() != 0)
            {
                foreach (var categories2 in listcategories2)
                {
                    listcatid.Add(categories2.Id);
                    //Cấp 3
                    List<Categories> listcategories3 = categoriesDAO.getListByPareantId(categories2.Id);
                    if (listcategories3.Count() != 0)
                    {
                        foreach (var categories3 in listcategories3)
                        {
                            listcatid.Add(categories3.Id);
                        }
                    }
                }
            }
            ProductsDAO productsDAO = new ProductsDAO();
            List<ProductInfo> list = productsDAO.getListByListCatId(listcatid, 10);
            return View("ProductCategory", list);
        }
        /////////////////////////////////////////////////////////////////////////////
        //Site/PostTopic
        public ActionResult PostTopic(string slug)
        {
            return View("PostTopic");
        }
        /////////////////////////////////////////////////////////////////////////////
        //Site/PostPage
        public ActionResult PostPage(string slug)
        {
            PostsDAO postsDAO = new PostsDAO();
            Posts posts = postsDAO.getRow(slug);
            return View("PostPage", posts);
        }
        /////////////////////////////////////////////////////////////////////////////
        //Site/Error404
        public ActionResult Error404(string slug)
        {
            return View("Error404");
        }
        /////////////////////////////////////////////////////////////////////////////
        //Product/Details
        public ActionResult ProductDetail(string slug)
        {
            //Hiển thị nội dung của sản phẩm
            ProductsDAO productsDAO = new ProductsDAO();
            List<ProductInfo> list = productsDAO.GetProductDetailBySlug(slug);
            //Lấy CatID của sản phẩm hiện tại
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            int catid = list.First().CatID;
            //Lấy danh sách sản phẩm cùng loại (related products)
            List<ProductInfo> relatedProducts = productsDAO.GetProductDetailByCategoryId(catid);
            //Truyền danh sách sản phẩm cùng loại cho View
            ViewBag.RelatedProducts = relatedProducts;
            //Trả về danh sách chi tiết sản phẩm cho List
            return View("ProductDetail", list);
        }
        /////////////////////////////////////////////////////////////////////////////
        //Post/Details
        public ActionResult PostDetail(Posts posts)
        {
            return View("PostDetail");
        }
        /////////////////////////////////////////////////////////////////////////////
        //HomeProduct
        public ActionResult HomeProduct(int id)
        {
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            Categories categories = categoriesDAO.getRow(id);
            ViewBag.Categories = categories;
            //Hiển thị toàn bộ các sản phẩm ứng với từng loại sản phẩm
            //Hiển thị the 3 cấp: Cha - Con - Con của con
            List<int> listcatid = new List<int>();
            //Cấp 1
            listcatid.Add(id);
            //Cấp 2
            List<Categories> listcategories2 = categoriesDAO.getListByPareantId(id);
            if (listcategories2.Count() != 0)
            {
                foreach (var categories2 in listcategories2)
                {
                    listcatid.Add(categories2.Id);
                    //Cấp 3
                    List<Categories> listcategories3 = categoriesDAO.getListByPareantId(categories2.Id);
                    if (listcategories3.Count() != 0)
                    {
                        foreach (var categories3 in listcategories3)
                        {
                            listcatid.Add(categories3.Id);
                        }
                    }
                }
            }
            ProductsDAO productsDAO = new ProductsDAO();
            List<ProductInfo> list = productsDAO.getListByListCatId(listcatid, 10);
            return View("HomeProduct", list);
        }

        /////////////////////////////////////////////////////////////////////////////
        ///Hiển thị trang sản phẩm được cung cấp bởi từng nhà cung cấp 
        public ActionResult ProductSupplier(string slug)
        {
            SuppliersDAO suppliersDAO = new SuppliersDAO();
            Suppliers suppliers = suppliersDAO.getRow(slug);
            ViewBag.Supplier = suppliers;
            ProductsDAO productsDAO = new ProductsDAO();
            List<Products> list = productsDAO.GetProductByID(suppliers.Id);
            return View("ProductSupplier", list);
        }
        public ActionResult Gioithieu()
        {
            return View();
        }
        public ActionResult Lienhe()
        {
            return View();
        }
        public ActionResult Blog()
        {
            return View();
        }
    }
}

THPTUDWeb/Views/Site/Home.cshtml
@model IEnumerable<MyClass.Model.Categories>
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";


}
<body>
    <main class="site-main">
        @*================ Hero banner start =================*@
        <section class="hero-banner">
            <div class="container">
                <div class="row no-gutters align-items-center pt-60px pb-60px">
                    <div class="col-5 d-none d-sm-block">
                        <div class="hero-banner__img">
                            <img class="img-fluid" src="~/Public/img/home/banner.png" alt="">
                        </div>
                    </div>
                    <div class="col-sm-7 col-lg-6 offset-lg-1 pl-4 pl-md-5 pl-lg-0">
                        <div class="hero-banner__content">
                            <h3 style="font-style: italic; font-size: 40px">Tomorrow's Technology Today</h3>
                            <h5>Creating a Future You Can't Imagine</h5>
                            <h2>Cùng mua sắm với những sản phẩm cao cấp của chúng tôi</h2>
                            <p>Technology Store mang đến cho khách hàng những sản phẩm thiết bị di động có chất lượng cao để phục vụ tốt những nhu cầu của khách hàng.</p>
                            <a class="button button-hero" href="#all_product">Mua sắm ngay</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        @*================ Hero banner start =================*@

        @*================ Hero Carousel start =================*@
        @Html.Action("Slider", "Module")
        @*================ Hero Carousel end =================*@
        <section class="section-margin calc-60px">
            <div class="container">
                @foreach (var item in Model)
                {
                    @Html.Action("HomeProduct", "Site", new { @id = item.Id })
                }
            </div>
        </section>
        @*================ trending product section start =================*@
        @Html.Action("Product", "Site")
        @*================ trending product section end =================*@

        @*================ Subscribe section start =================*@
        <section class="subscribe-position">
            <div class="container">
                <div class="subscribe text-center">
                    <h3 class="subscribe__title">CẬP NHẬT THÔNG TIN MỚI NHẤT</h3>
                    <p>Hãy để lại Email của bạn để chúng tôi có thể sớm thông báo những thông tin mới sớm nhất</p>
                    <div id="mc_embed_signup">
                        <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe-form form-inline mt-5 pt-1">
                            <div class="form-group ml-sm-auto">
                                <input class="form-control mb-1" type="email" name="EMAIL" placeholder="Nhập Email của bạn" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Email Address '">
                                <div class="info"></div>
                            </div>
                            <button class="button button-subscribe mr-auto mb-1" type="submit">Đăng ký ngay</button>
                            <div style="position: absolute; left: -5000px;">
                                <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                            </div>

                        </form>
                    </div>

                </div>
            </div>
        </section>
        @*================ Subscribe section end =================*@
    </main>
</body>

THPTUDWeb/Views/Site/HomeProduct.cshtml
@model IEnumerable<MyClass.Model.ProductInfo>

@{
    var item = ViewBag.Categories;
}

<style>
    .custom-button {
        background-color: #8894FF;
        color: #ffffff;
        padding: 0.65em 0.8em 0.65em 0.8em;
    }
    .custom-button:hover {
        background-color: #384AEB;
    }
</style>

@if (Model.Count() != 0)
{

    <div class="section-intro pb-60px">
        <p><a href="~/@item.Slug">Danh mục sản phẩm theo loại</a></p>
        <h2>
            <span class="section-intro__style">@item.Name</span>
        </h2>
    </div>
    <div class="row">
        @foreach (var product in Model)
        {
            <div class="col-md-6 col-lg-4 col-xl-3">
                <div class="card text-center card-product">
                    <div class="card-product__img">
                        <img class="card-img" src="Public/img/product/@product.Image" alt="">
                        <ul class="card-product__imgOverlay">
                            <li>
                                <a href="@product.Slug">
                                <span class="custom-button"><i class="ti-search"></i></span>
                                </a>
                            </li>
                            <li><a href="@Url.Action("AddCart","Giohang", new { productid   = product.Id })">
                                <span class="custom-button"><i class="ti-shopping-cart"></i></span>
                                </a></li>
                            <li><button><i class="ti-heart"></i></button></li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <h4 class="card-product__title"><a href="@product.Slug">@product.Name</a></h4>
                        <p strong class="card-product__price text-success">@string.Format("{0:0,00}", @product.SalePrice)<sup>đ</sup></p>
                        <del><span class="danger card-product__price text-danger">@string.Format("{0:0,00}", @product.Price)</span></del><sup>đ</sup>
                    </div>
                </div>
            </div>
        }
    </div>
}

THPTUDWeb/Views/Site/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<h2>INDEX</h2>

THPTUDWeb/Views/Site/PostPage.cshtml
@model MyClass.Model.Posts
@{
    ViewBag.Title = "PostPage";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<body>
    <!-- ================ start banner area ================= -->
    <section class="blog-banner-area" id="blog">
        <div class="container h-100">
            <div class="blog-banner">
                <div class="text-center">
                    <h1>@Model.Title</h1>
                    <nav aria-label="breadcrumb" class="banner-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Chi tiết bài viết</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ end banner area ================= -->
    <!--================Blog Area =================-->
    <section class="blog_area single-post-area py-80px section-margin--small">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="single-post row">
                        <div class="col-lg-12">
                            <div class="feature-img">
                                <img class="img-fluid" src="~/Public/img/page/@Model.Image" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget post_category_widget">
                            @Html.Action("PageList", "Module")
                        </aside>
                    </div>
                </div>
            </div>
            <div>
                @if (Model.Title == "Giới thiệu")
                {
                    @Html.Action("Gioithieu", "Site")
                }
                else if (Model.Title == "Liên hệ")
                {
                    @Html.Action("Lienhe", "Site")
                }
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
</body>

THPTUDWeb/Views/Site/PostTopic.cshtml
@{
    ViewBag.Title = "PostTopic";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<h2>PostTopic</h2>

THPTUDWeb/Views/Site/ProductCategory.cshtml
@model IEnumerable<MyClass.Model.ProductInfo>

@{
    var item = ViewBag.Categories;
}

@{
    ViewBag.Title = item.Name;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<style>
    .custom-button {
        background-color: #8894FF;
        color: #ffffff;
        padding: 0.65em 0.8em 0.65em 0.8em;
    }

        .custom-button:hover {
            background-color: #384AEB;
        }
</style>

<body>
    <!-- ================ start banner area ================ -->
    <section class="blog-banner-area" id="category">
        <div class="container h-100">
            <div class="blog-banner">
                <div class="text-center">
                    <h1 class="text-uppercase">@item.Name</h1>
                    <nav aria-label="breadcrumb" class="banner-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">@item.Name</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ end banner area ================= -->
    <!-- ================ category section start ================= -->
    <section class="section-margin--small mb-5">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-4 col-md-5">
                    @* Category List Begin *@
                    @Html.Action("CategoriesList", "Module")
                </div>
                @* Category List End *@

                <div class="col-xl-9 col-lg-8 col-md-7">
                    <!-- Start Best Seller -->
                    <section class="lattest-product-area pb-40 category-list">
                        <div class="row">
                            @foreach (var product in Model)
                            {
                                <div class="col-md-6 col-lg-4">
                                    <div class="card text-center card-product">
                                        <div class="card-product__img">
                                            <img class="card-img" src="Public/img/product/@product.Image" alt="">
                                            <ul class="card-product__imgOverlay">
                                                <li>
                                                    <a href="@product.Slug">
                                                        <span class="custom-button"><i class="ti-search"></i></span>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("AddCart","Giohang", new { productid   = product.Id })">
                                                        <span class="custom-button"><i class="ti-shopping-cart"></i></span>
                                                    </a>
                                                </li>
                                                <li><button><i class="ti-heart"></i></button></li>
                                            </ul>
                                        </div>
                                        <div class="card-body">
                                            <p>Accessories</p>
                                            <h4 class="card-product__title"><a href="@product.Slug">@product.Name</a></h4>
                                            <p strong class="card-product__price text-success">@string.Format("{0:0,00}", product.SalePrice)<sup>đ</sup></p>
                                            <del><span class="danger card-product__price text-danger">@string.Format("{0:0,00}", product.Price)</span></del><sup>đ</sup>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </section><!-- End Best Seller -->
                </div>
            </div>
        </div>
    </section>
    <!-- ================ category section end ================= -->
</body>

THPTUDWeb/Views/Site/ProductSupplier.cshtml
@model IEnumerable<MyClass.Model.Products>

@{
    var item = ViewBag.Supplier;
}

@{
    ViewBag.Title = item.Name;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<style>
    .custom-button {
        background-color: #8894FF;
        color: #ffffff;
        padding: 0.65em 0.8em 0.65em 0.8em;
    }

        .custom-button:hover {
            background-color: #384AEB;
        }
</style>
<body>
    <!-- ================ start banner area ================ -->
    <section class="blog-banner-area" id="supplier">
        <div class="container h-100">
            <div class="blog-banner">
                <div class="text-center">
                    <h1 class="text-uppercase">Các sản phẩm đến từ @item.Name</h1>
                    <nav aria-label="breadcrumb" class="banner-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">@item.Name</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ end banner area ================= -->
    <!-- ================ category section start ================= -->
    <section class="section-margin--small mb-5">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-4 col-md-5">
                    @* Category List Begin *@
                    @Html.Action("SuppliersList", "Module")
                </div>
                @* Category List End *@

                <div class="col-xl-9 col-lg-8 col-md-7">
                    <!-- Start Best Seller -->
                    <section class="lattest-product-area pb-40 category-list">
                        <div class="row">
                            @foreach (var product in Model)
                            {
                                <div class="col-md-6 col-lg-4">
                                    <div class="card text-center card-product">
                                        <div class="card-product__img">
                                            <img class="card-img" src="Public/img/product/@product.Image" alt="">
                                            <ul class="card-product__imgOverlay">
                                                <li>
                                                    <a href="@product.Slug">
                                                        <span class="custom-button"><i class="ti-search"></i></span>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("AddCart","Giohang", new { productid   = product.Id })">
                                                        <span class="custom-button"><i class="ti-shopping-cart"></i></span>
                                                    </a>
                                                </li>
                                                <li><button><i class="ti-heart"></i></button></li>
                                            </ul>
                                        </div>
                                        <div class="card-body">
                                            <h4 class="card-product__title"><a href="@product.Slug">@product.Name</a></h4>
                                            <p strong class="card-product__price text-success">@string.Format("{0:0,00}", product.SalePrice)<sup>đ</sup></p>
                                            <del><span class="danger card-product__price text-danger">@string.Format("{0:0,00}", product.Price)</span></del><sup>đ</sup>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </section><!-- End Best Seller -->
                </div>
            </div>
        </div>
    </section>
    <!-- ================ category section end ================= -->
</body>