THPTUDWeb/Areas/Admin/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyClass.Model;
using MyClass.DAO;
using THPTUDWeb.Library;

namespace THPTUDWeb.Areas.Admin.Controllers
{
    public class TopicController : Controller
    {
        TopicsDAO topicsDAO = new TopicsDAO();
        LinksDAO linksDAO = new LinksDAO();
        //////////////////////////////////////////////////////////////////////
        // GET: Admin/Category/Index: Trả về danh sách các mẩu tin
        public ActionResult Index()
        {
            //Hiển thị toàn bộ danh sách các chủ đề
            return View(topicsDAO.getList("Index"));
        }

        //////////////////////////////////////////////////////////////////////
        // GET: Admin/Category/Details/5: Hiển thị thông tin một mẩu tin
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["message"] = new XMessage("danger", "Không tìm thấy chủ đề bài viết");
                return RedirectToAction("Index");
            }
            Topics topics = topicsDAO.getRow(id);
            if (topics == null)
            {
                TempData["message"] = new XMessage("danger", "Không tìm thấy chủ đề bài viết");
                return RedirectToAction("Index");
            }
            return View(topics);
        }

        // GET: Admin/Category/Create
        public ActionResult Create()
        {
            ViewBag.TopicList = new SelectList(topicsDAO.getList("Index"), "Id", "Name");
            ViewBag.OrderList = new SelectList(topicsDAO.getList("Index"), "Order", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Topics topics)
        {
            if (ModelState.IsValid)
            {
                //Xử lý tự động cho các trường sau:
                //-----Create At
                topics.CreateAt = DateTime.Now;
                //-----Create By
                topics.CreateBy = Convert.ToInt32(Session["UserID"]);
                //-----Slug
                topics.Slug = XString.Str_Slug(topics.Name);
                //-----ParentID
                if (topics.ParentID == null)
                {
                    topics.ParentID = 0;
                }
                //-----Order
                if (topics.Order == null)
                {
                    topics.Order = 1;
                }
                else
                {
                    topics.Order += 1;
                }
                //-----UpdateAt
                topics.UpdateAt = DateTime.Now;
                //-----UpdateBy
                topics.UpdateBy = Convert.ToInt32(Session["UserID"]);
                //-----Xử lý mục Topics
                if (topicsDAO.Insert(topics) == 1)       //Nếu thêm dữ liệu thành công
                {
                    Links links = new Links();
                    links.Slug = topics.Slug;
                    links.TableID = topics.Id;
                    links.Type = "topic";
                    linksDAO.Insert(links);
                }
                //Hiển thị thông báo thành công
                TempData["message"] = new XMessage("success", "Thêm chủ đề bài viết mới thành công");
                return RedirectToAction("Index");
            }
            ViewBag.TopicList = new SelectList(topicsDAO.getList("Index"), "Id", "Name");
            ViewBag.OrderList = new SelectList(topicsDAO.getList("Index"), "Order", "Name");
            return View(topics);
        }

        //////////////////////////////////////////////////////////////////////
        // GET: Admin/Category/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.TopicList = new SelectList(topicsDAO.getList("Index"), "Id", "Name");
            ViewBag.OrderList = new SelectList(topicsDAO.getList("Index"), "Order", "Name");
            if (id == null)
            {
                TempData["message"] = new XMessage("danger", "Cập nhật trạng thái thất bại");
                return RedirectToAction("Index");
            }
            Topics topics = topicsDAO.getRow(id);
            if (topics == null)
            {
                TempData["message"] = new XMessage("danger", "Cập nhật trạng thái thất bại");
                return RedirectToAction("Index");
            }
            return View(topics);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Topics topics)
        {
            if (ModelState.IsValid)
            {
                //Xử lý tự động cho các trường sau:
                //-----Create At
                topics.CreateAt = DateTime.Now;
                //-----Create By
                topics.CreateBy = Convert.ToInt32(Session["UserID"]);
                //-----Slug
                topics.Slug = XString.Str_Slug(topics.Name);
                //-----ParentID
                if (topics.ParentID == null)
                {
                    topics.ParentID = 0;
                }
                //-----Order
                if (topics.Order == null)
                {
                    topics.Order = 1;
                }
                else
                {
                    topics.Order += 1;
                }
                //-----UpdateAt
                topics.UpdateAt = DateTime.Now;
                //-----UpdateBy
                topics.UpdateBy = Convert.ToInt32(Session["UserID"]);
                //Cập nhật dữ liệu, sửa thêm phần Links phục vụ cho Topics
                //Nếu trùng khớp thông tin: Type = category & TableID = topics.ID
                Links links = linksDAO.getRow(topics.Id, "category");
                if (topicsDAO.Update(topics) == 1)
                {
                    //Cập nhật dữ liệu
                    links.Slug = topics.Slug;
                    linksDAO.Update(links);
                }
                //Hiển thị thông báo thành công
                TempData["message"] = new XMessage("success", "Sửa chủ đề bài viết thành công");

                return RedirectToAction("Index");
            }
            return View(topics);
        }

        //////////////////////////////////////////////////////////////////////
        // GET: Admin/Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                //Thông báo thất bại
                TempData["message"] = new XMessage("danger", "Xoá chủ đề bài viết thất bại");
                //Chuyển hướng trang
                return RedirectToAction("Trash");
            }
            Topics topics = topicsDAO.getRow(id);
            if (topics == null)
            {
                //Thông báo thất bại
                TempData["message"] = new XMessage("danger", "Xoá chủ đề bài viết thất bại");
                //Chuyển hướng trang
                return RedirectToAction("Trash");
            }
            return View(topics);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Topics topics = topicsDAO.getRow(id);
            //Tìm thấy mẩu tin => xoá, cập nhật cho Links
            if (topicsDAO.Delete(topics) == 1)
            {
                Links links = linksDAO.getRow(topics.Id, "topic");
                //Xoá luôn cho Links
                linksDAO.Delete(links);
            }
            //Hiển thị thông báo
            TempData["message"] = new XMessage("success", "Xoá chủ dề bài viết thành công");
            return RedirectToAction("Trash");
        }

        //////////////////////////////////////////////////////////////////////
        // GET: Admin/Category/Status/5
        public ActionResult Status(int? id)
        {
            if (id == null)
            {
                //Thông báo thất bại
                TempData["message"] = new XMessage("danger", "Cập nhật trạng thái thất bại");
                //Chuyển hướng trang
                return RedirectToAction("Index");
            }
            Topics topics = topicsDAO.getRow(id);
            if (topics == null)
            {
                //Thông báo thất bại
                TempData["message"] = new XMessage("danger", "Cập nhật trạng thái thất bại");
                //Chuyển hướng trang
                return RedirectToAction("Index");
            }
            //Cập nhật trạng thái
            topics.Status = (topics.Status == 1) ? 2 : 1;
            //Cập nhật UpdateBy
            topics.UpdateBy = Convert.ToInt32(Session["UserId"].ToString());
            //Cập nhật UpdateAt
            topics.UpdateAt = DateTime.Now;
            //Update Database
            topicsDAO.Update(topics);
            //Hiển thị thông báo thành công
            TempData["message"] = new XMessage("success", "Cập nhật trạng thái thành công");
            //Trở về trang Index
            return RedirectToAction("Index");
        }

        //////////////////////////////////////////////////////////////////////
        // GET: Admin/Category/DelTrash/5
        public ActionResult DelTrash(int? id)
        {
            if (id == null)
            {
                //Thông báo thất bại
                TempData["message"] = new XMessage("danger", "Xoá chủ đề bài viết thất bại");
                //Chuyển hướng trang
                return RedirectToAction("Index");
            }
            Topics topics = topicsDAO.getRow(id);
            if (topics == null)
            {
                //Thông báo thất bại
                TempData["message"] = new XMessage("danger", "Xoá chủ đề bài viết thất bại");
                //Chuyển hướng trang
                return RedirectToAction("Index");
            }
            //Cập nhật trạng thái
            topics.Status = 0;
            //Cập nhật UpdateBy

THPTUDWeb/Areas/Admin/Views/Topic/Create.cshtml
@model MyClass.Model.Topics

@{
    ViewBag.Title = "Thêm mới chủ đề bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="wrapper">
        <!-- Main Sidebar Container -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-6">
                                <strong class="text-danger">THÊM MỚI CHỦ ĐỀ BÀI VIẾT</strong>
                            </div>
                            <div class="col-md-6 text-right">
                                <a href="@Url.Action("Index","Topic")" class="btn-sm btn-info"><i class="fa fa-long-arrow-alt-left"> Quay lại</i></a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            @*Phần nhập dữ liệu bằng tay*@
                            <div class="col-md-9">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.MetaDesc, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.MetaDesc, new { @class = "form-control", @row = "5" })
                                        @Html.ValidationMessageFor(model => model.MetaDesc, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.MetaKey, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.MetaKey, new { @class = "form-control", @row = "5" })
                                        @Html.ValidationMessageFor(model => model.MetaKey, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            @*Phần lựa chọn dữ liệu*@
                            <div class="col-md-3">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ParentID, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.ParentID, (SelectList)ViewBag.TopicList, "Cấp 0", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.Order, (SelectList)ViewBag.OrderList, "Sắp xếp", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.Status, new[] { new SelectListItem { Text = "Không xuất bản", Value = "2" }, new SelectListItem { Text = "Xuất bản", Value = "1" } }, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>

                        @*Sua nut Create*@
                        <button class="btn-sm btn-success" type="submit" name="create">[Lưu] Thêm <i class="fa fa-save"></i></button>

                    </div> <!-- /.card-footer-->
                </div><!-- /.card -->
            </section><!-- /.content -->
        </div> <!-- /.content-wrapper -->
    </div><!-- ./wrapper -->
}

THPTUDWeb/Areas/Admin/Views/Topic/Delete.cshtml
@model MyClass.Model.Topics

@{
    ViewBag.Title = "Xác nhận xoá chủ đề bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section header {
    <link href="~/Public/css/jquery.dataTables.min.css" rel="stylesheet" />
}

@section footer {
    <script src="~/Public/js/jquery.dataTables.min.js"></script>
    <script>let table = new DataTable('#myTable');</script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content my-2">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <strong class="text-danger">XÁC NHẬN XOÁ CHỦ ĐỀ BÀI VIẾT</strong>
                        </div>
                        <div class="col-md-6 text-right">
                            <a href="@Url.Action("Index", "Topic")" class="btn-sm btn-info"> <i class="fa fa-long-arrow-alt-left"></i> Quay lại</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Id)</th>
                                <th>@Html.DisplayNameFor(model => model.Name)</th>
                                <th>@Html.DisplayNameFor(model => model.Slug)</th>
                                <th>@Html.DisplayNameFor(model => model.ParentID)</th>
                                <th>@Html.DisplayNameFor(model => model.Order)</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td>@Html.DisplayFor(model => model.Id)</td>
                                <td>@Html.DisplayFor(model => model.Name)</td>
                                <td>@Html.DisplayFor(model => model.Slug)</td>
                                <td>@Html.DisplayFor(model => model.ParentID)</td>
                                <td>@Html.DisplayFor(model => model.Order)</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="form-actions no-color">
                        <button class="btn-sm btn-danger" type="submit" name="save">Xoá [Delete] <i class="fa fa-trash"></i> </button>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
            <!-- /.card -->
        </section>
        <!-- /.content -->
    </div><!-- /.content-wrapper -->
}

THPTUDWeb/Areas/Admin/Views/Topic/Details.cshtml
@model MyClass.Model.Topics

@{
    ViewBag.Title = "Chi tiết chủ đề bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    <!-- Main content -->
    <section class="content my-2">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <strong class="text-danger">CHI TIẾT CHỦ ĐỀ BÀI VIẾT</strong>
                    </div>
                    <div class="col-md-6 text-right">
                        <a href="@Url.Action("Edit","Topic",  new { id = Model.Id })" class="btn-sm btn-success"> <i class="fa fa-edit"> Sửa</i></a>
                        <a href="@Url.Action("Index","Topic")" class="btn-sm btn-info"> <i class="fa fa-long-arrow-alt-left"></i> Quay lại</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Id)</th>
                            <th>@Html.DisplayNameFor(model => model.Name)</th>
                            <th>@Html.DisplayNameFor(model => model.Slug)</th>
                            <th>@Html.DisplayNameFor(model => model.ParentID)</th>
                            <th>@Html.DisplayNameFor(model => model.Order)</th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <td>@Html.DisplayFor(model => model.Id)</td>
                            <td>@Html.DisplayFor(model => model.Name)</td>
                            <td>@Html.DisplayFor(model => model.Slug)</td>
                            <td>@Html.DisplayFor(model => model.ParentID)</td>
                            <td>@Html.DisplayFor(model => model.Order)</td>
                        </tr>
                    </tbody>
                </table>
                <!-- /.card-body -->
            </div>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

THPTUDWeb/Areas/Admin/Views/Topic/Edit.cshtml
@model MyClass.Model.Topics

@{
    ViewBag.Title = "Thay đổi thông tin chủ đề bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id);
    @Html.HiddenFor(model => model.CreateAt);
    @Html.HiddenFor(model => model.CreateBy);

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content my-2">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <strong class="text-danger">CHỈNH SỬA CHỦ ĐỀ BÀI VIẾT</strong>
                        </div>
                        <div class="col-md-6 text-right">
                            <a href="@Url.Action("Index", "Topic")" class="btn-sm btn-info"> <i class="fa fa-long-arrow-alt-left"></i> Quay lại</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    @*Phan NOI DUNG*@
                    <div class="row">
                        @* Phần nhập tay *@
                        <div class="col-md-9">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MetaDesc, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.MetaDesc, new { @class = "form-control", @row = "5" })
                                    @Html.ValidationMessageFor(model => model.MetaDesc, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MetaKey, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.MetaKey, new { @class = "form-control", @row = "5" })
                                    @Html.ValidationMessageFor(model => model.MetaKey, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        @* Phần lựa chọn *@
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ParentID, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.ParentID, (SelectList)ViewBag.TopicList, "Cấp 0", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Order, (SelectList)ViewBag.OrderList, "Sắp xếp", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Status, new[] { new SelectListItem { Text = "Không xuất bản", Value = "2" }, new SelectListItem { Text = "Xuất bản", Value = "1" } }, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button class="btn-sm btn-success" type="submit" name="create"> Lưu <i class="fa fa-save"></i> </button>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
                <!-- /.card -->
            </div>
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
}

THPTUDWeb/Areas/Admin/Views/Topic/Index.cshtml
@model IEnumerable<MyClass.Model.Topics>

@{
    ViewBag.Title = "Danh sách chủ đề bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section header {
    <link href="~/Public/css/jquery.dataTables.min.css" rel="stylesheet" />
}

@section footer {
    <script src="~/Public/js/jquery.dataTables.min.js"></script>
    <script>let table = new DataTable('#myTable');</script>
}

<div class="wrapper">
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <strong class="text-danger">DANH MỤC CHỦ ĐỀ BÀI VIẾT</strong>
                        </div>
                        <div class="col-md-6 text-right">
                            <a href="@Url.Action("Create", "Topic")" class="btn-sm btn-success"><i class="fa fa-plus"> Thêm mới</i></a>
                            <a href="@Url.Action("Trash", "Topic")" class="btn-sm btn-danger"><i class="fa fa-trash"></i> Thùng rác</a>

                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @*Hiển thị dòng thông báo*@
                    @Html.Partial("Message")
                    <table class="table table-bordered table-striped" id="myTable">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Id)</th>
                                <th>@Html.DisplayNameFor(model => model.Name)</th>
                                <th>@Html.DisplayNameFor(model => model.Slug)</th>
                                <th>@Html.DisplayNameFor(model => model.ParentID)</th>
                                <th>@Html.DisplayNameFor(model => model.Order)</th>
                                <th>Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Slug)</td>
                                    <td>@Html.DisplayFor(modelItem => item.ParentID)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Order)</td>
                                    <td>
                                        @if (item.Status == 1)
                                        {
                                            <a href="@Url.Action("Status", "Topic", new { id = item.Id })" class="btn-sm btn-success"><i class="fa fa-toggle-on"></i></a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("Status", "Topic", new { id = item.Id })" class="btn-sm btn-danger"><i class="fa fa-toggle-off"></i></a>
                                        }
                                        <a href="@Url.Action("Edit", "Topic", new { id = item.Id })" class="btn-sm btn-primary"><i class="fa fa-edit"></i></a>
                                        <a href="@Url.Action("Details", "Topic", new { id = item.Id })" class="btn-sm btn-info"><i class="fa fa-eye"></i></a>
                                        <a href="@Url.Action("DelTrash", "Topic",  new { id = item.Id })" class="btn-sm btn-danger"><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div> <!-- /.card-footer-->
            </div><!-- /.card -->
        </section><!-- /.content -->
    </div> <!-- /.content-wrapper -->
</div><!-- ./wrapper -->